Vagrant.configure("2") do |config|
    (1..3).each do |i|
        config.vm.define "swarm-#{i}" do |swarm|
            swarm.vm.box = "debian/bookworm64"
            swarm.vm.hostname = "node-#{i}"
            swarm.vm.network "private_network", ip: "172.89.0.2#{i}"

            swarm.ssh.insert_key = false
            swarm.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_ed25519']
            swarm.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "~/.ssh/authorized_keys"

            config.vm.provision "shell", inline: <<-SHELL
            apt-get update 
            apt-get install curl vim -y
            curl -fsSL https://get.docker.com | sh 
            usermod -a -G docker vagrant
          SHELL
        end
    end
end



            
